### ISSUE TITLE
Add ability to restart VMs

### ISSUE THREAD

**Issue by r7vme** [giantswarm/k8s-kvm#4]
Current implementation will remove the disk.

Best way would be just to check ROOTFS path for existance

https://github.com/giantswarm/k8s-kvm/blob/master/docker-entrypoint.sh#L56

**Comment by r7vme** [comment]
cc: @teemow @calvix @xh3b4sd 

I would say this is critical.

**Comment by calvix** [comment]
I think we want VM to be ephemeral, so `restart == new machine`, why would you need restart vm for?

**Comment by r7vme** [comment]
I agree for workers, but for master we need at least etcd stuff.

**Comment by xh3b4sd** [comment]
Etcd data should be backed by persistent volumes.

**Comment by r7vme** [comment]
Yes, i've tested that graceful reboot works fine for workers and master(just in case we'll need one for debuging). Pod restart works fine for worker (loses all ephemeral data), but master pods restart test failed. See issues below.

This issue can be closed, but following in favor following two
https://github.com/giantswarm/kvm-operator/issues/121
https://github.com/giantswarm/kvm-operator/issues/122
