### ISSUE TITLE
reduce flannel network from /16 to smaller

### ISSUE THREAD

**Issue by calvix** [giantswarm/k8s-kvm#7]
Towards https://github.com/giantswarm/giantswarm/issues/1709

We kinda overbook subnets for flannel, and we are not going go get a lot of `/16` for each guest cluster from our customers.

We need 4 IPs == `/30` per node (atm we run only 1 worker on 1 machine, if we want to change this we may wanna increase this)

 If we move from `/16` to `/20` we are able to have `1024`  k8s nodes (each machine has flannel daemon sets so that is `/30` per node) which should be fine for quite some time.

And we got 16x more possible geust clusters, so if the customer gives us 5x/`16` we can spawn 80 clusters which are more reasonable limit than 5.

**Comment by calvix** [comment]
ping @kopiczko @teemow @xh3b4sd @r7vme

**Comment by xh3b4sd** [comment]
@calvix is it easy enough to change the subnet in the configmap or is there something else we also have to do?

**Comment by calvix** [comment]
Unfortunately, this needs more work, because atm we only iterate like this:
from `10.%d.0.0` to
`10.0.0.0/16`
`10.1.0.0/16`
`10.2.0.0/16`
...


To solve this issue we would need to specify
* avaiable range for flannel (ie `10.0.0.0/12` or `172.20.0.0/14`)
* flannel cluster subnet length ( ie `/22` or even `24` , current is `16` which is too big)
instead of start end end VNI

And then flannel operator will  generate subnets from the avaiable subnet pool.
example for `172.20.0.0/14` subnet pool and `/22` cluster subnet length:
`172.20.0.0/22`
`172.20.4.0/22`
`172.20.8.0/22`
`172.20.12.0/22`

example for `172.20.0.0/14` subnet pool and `24` custer subnet length
`172.20.0.0/24`
`172.20.1.0/24`
`172.20.2.0/24`
`172.20.3.0/24`

This require some changes to the code and the way how are the subnets useds. Also we would need to work with the `net` libraries of go to have this easier done.
In addition VNI cannot be easily mapped  like before (it was mapped to the  subnet number as it was easy and unique)

**Comment by teemow** [comment]
In general we have a very similar issue on AWS. Imo it would be good to put IPAM into a separate component that can be used in both environments. 

Problem on AWS:
To peer the vpcs with the host cluster we need to have distinct subnet ranges for each guest cluster. So we need to get a range and divide it into smaller ones and handing that over to the aws-operator. The aws-operator can then further divide that range into eg availability zones etc. Afaik kubernetesd writes the subnet configuration into the cluster tpr for the aws operator. 

How about solving this for both solutions?

**Comment by JosephSalisbury** [comment]
I think we'll need a /16 for the aws operator, and then a /24 for each vpc
Makes sense that we reuse the same stuff for kvm, and give each flannel network a /24

**Comment by teemow** [comment]
Whether it is /24 or /16 should be configurable imo. So we are flexible across installations. And it could be solved for both platforms at once.

**Comment by calvix** [comment]
I think this should be in operator board, sync `flannel operator` will be dealing with this.

**Comment by calvix** [comment]
And it's blocker for Adidas on-prem. so it should probably have high priority.

**Comment by calvix** [comment]
@JosephSalisbury is working on the concept.

**Comment by calvix** [comment]
@JosephSalisbury any ETA?

**Comment by JosephSalisbury** [comment]
Should be able to land this week

**Comment by calvix** [comment]
closing @JosephSalisbury
