### ISSUE TITLE
gpg check on coreos image before starting KVM

### ISSUE THREAD

**Issue by calvix** [giantswarm/k8s-kvm#8]
for the security reason, it would be good to always check gpg on the CoreOS Container Linux image before starting KVM

should be easy to done, and it's something enterprise customers want

**Comment by xh3b4sd** [comment]
Can you provide information on how to do this? Then we can just pick it.

**Comment by calvix** [comment]
So this issue was created before I did more research.
Problem is that the original images are customized to fit our needs and we cannot verify the integrity via gpg. I think this is not doable so we can close.

**Comment by xh3b4sd** [comment]
I think it is a good goal to have some secure boot functionality. Uncertain how to do this though. Lets close this issue for now and come back when there is a more concrete idea and/or need.
